// SPDX-License-Identifier: AGPL-3.0-or-later
//! Operator knowledge for `copybook explain`.
//!
//! DO NOT EDIT. Source: `docs/reference/ERROR_CODES.md`.
//! Regenerate: `cargo run -p xtask -- explain sync-knowledge`.
//! Freshness is enforced by `docs verify-all` (`explain-knowledge`).

/// One operator knowledge row: what a stable error means and how to fix it.
pub struct Explanation {
    /// Full stable error identity (e.g. `CBKE501_JSON_TYPE_MISMATCH`).
    pub code: &'static str,
    /// Severity verbatim from the error-code reference.
    pub severity: &'static str,
    /// What the error means, verbatim from the reference.
    pub description: &'static str,
    /// Diagnostic context the error carries, verbatim.
    pub context: &'static str,
    /// Operator remediation, verbatim from the reference.
    pub resolution: &'static str,
}

/// Full operator knowledge, sorted by code for determinism.
pub const EXPLANATIONS: &[Explanation] = &[
    Explanation {
        code: "CBKA001_BASELINE_ERROR",
        severity: "Error",
        description: "Performance baseline operation failed (baseline file could not be read, parsed, serialized, or written)",
        context: "Baseline file path, underlying I/O or serialization error",
        resolution: "Check that the baseline file exists, is valid JSON, and is writable",
    },
    Explanation {
        code: "CBKC201_JSON_WRITE_ERROR",
        severity: "Fatal",
        description: "Error writing JSON output data",
        context: "Record number, I/O error details",
        resolution: "Check output file permissions or disk space",
    },
    Explanation {
        code: "CBKC301_INVALID_EBCDIC_BYTE",
        severity: "Warning (replace mode), Fatal (error mode)",
        description: "Invalid EBCDIC byte encountered during conversion",
        context: "Record number, field path, byte offset, hex value",
        resolution: "Fix data corruption or use replacement mode",
    },
    Explanation {
        code: "CBKD101_INVALID_FIELD_TYPE",
        severity: "Fatal",
        description: "Invalid field type encountered during processing",
        context: "Record number, field path, field type",
        resolution: "Check schema definition and field type compatibility",
    },
    Explanation {
        code: "CBKD301_RECORD_TOO_SHORT",
        severity: "Fatal",
        description: "Record data is too short for the required field data or LRECL",
        context: "Record number, field path (when field-level), expected vs actual byte count",
        resolution: "Check data integrity, file transfer mode (binary vs text), record boundaries, or LRECL specification; use `copybook inspect` to verify expected record size",
    },
    Explanation {
        code: "CBKD302_EDITED_PIC_NOT_IMPLEMENTED",
        severity: "Legacy, not emitted by current decode paths",
        description: "Legacy taxonomy identifier retained for compatibility; current edited PIC decode is implemented in Phase E2 and does not emit CBKD302",
        context: "Historical Phase E1 edited PIC decode boundary",
        resolution: "Use the current edited PIC diagnostics: CBKD421 for invalid format, CBKD422 for sign mismatch, and CBKD423 for blank-when-zero warnings",
    },
    Explanation {
        code: "CBKD401_COMP3_INVALID_NIBBLE",
        severity: "Fatal (strict), Warning (lenient)",
        description: "Invalid nibble in packed decimal field",
        context: "Record number, field path, byte offset, nibble value",
        resolution: "Fix data corruption",
    },
    Explanation {
        code: "CBKD410_ZONED_OVERFLOW",
        severity: "Error",
        description: "Zoned decimal value exceeded numeric capacity during decode",
        context: "Record number, field path, digit count",
        resolution: "Verify the PIC clause digit count matches the data, check for corruption",
    },
    Explanation {
        code: "CBKD411_ZONED_BAD_SIGN",
        severity: "Fatal (strict), Warning (lenient)",
        description: "Invalid sign zone in zoned decimal field or ASCII overpunch character",
        context: "Record number, field path, byte offset, zone/character value",
        resolution: "Fix data corruption, verify codepage (EBCDIC vs ASCII), or check overpunch encoding",
    },
    Explanation {
        code: "CBKD412_ZONED_BLANK_IS_ZERO",
        severity: "Warning",
        description: "BLANK WHEN ZERO field contains all spaces",
        context: "Record number, field path",
        resolution: "Normal behavior, no action needed",
    },
    Explanation {
        code: "CBKD413_ZONED_INVALID_ENCODING",
        severity: "Error",
        description: "Invalid zoned decimal encoding format detected (bytes match neither the expected EBCDIC nor ASCII zoned layout)",
        context: "Record number, field path, byte values",
        resolution: "Verify codepage selection and zoned encoding options, inspect raw bytes with `--emit-raw`",
    },
    Explanation {
        code: "CBKD414_ZONED_MIXED_ENCODING",
        severity: "Error",
        description: "Mixed ASCII/EBCDIC encoding detected within a single zoned decimal field",
        context: "Record number, field path, per-byte encoding classification",
        resolution: "Fix upstream data conversion so each field uses a single encoding, verify file transfer mode",
    },
    Explanation {
        code: "CBKD415_ZONED_ENCODING_AMBIGUOUS",
        severity: "Error",
        description: "Zoned encoding auto-detection failed or remains ambiguous",
        context: "Record number, field path",
        resolution: "Specify the zoned encoding explicitly instead of relying on auto-detection",
    },
    Explanation {
        code: "CBKD421_EDITED_PIC_INVALID_FORMAT",
        severity: "Fatal",
        description: "Data does not match edited PICTURE pattern (Phase E2 decode)",
        context: "Record number, field path, PIC pattern, actual data bytes",
        resolution: "Verify data format matches copybook PIC clause, check codepage conversion, inspect raw data with `--emit-raw`",
    },
    Explanation {
        code: "CBKD422_EDITED_PIC_SIGN_MISMATCH",
        severity: "Fatal",
        description: "Sign character mismatch in edited numeric field (expected +/-, CR, or DB)",
        context: "Record number, field path, expected sign, actual character",
        resolution: "Check sign editing in PIC clause matches data, verify codepage",
    },
    Explanation {
        code: "CBKD423_EDITED_PIC_BLANK_WHEN_ZERO",
        severity: "Warning (informational)",
        description: "Edited numeric field with BLANK WHEN ZERO is all blanks (decoded as zero)",
        context: "Record number, field path",
        resolution: "Expected behavior for BLANK WHEN ZERO fields, no action needed",
    },
    Explanation {
        code: "CBKD431_FLOAT_NAN",
        severity: "Reserved — not currently emitted (see note)",
        description: "Floating-point field (COMP-1/COMP-2) contains NaN; the value is decoded as JSON null",
        context: "Record number, field path",
        resolution: "Check upstream data generation for uninitialized float fields; null output is the documented behavior",
    },
    Explanation {
        code: "CBKD432_FLOAT_INFINITY",
        severity: "Reserved — not currently emitted (see note)",
        description: "Floating-point field (COMP-1/COMP-2) contains infinity; the value is decoded as JSON null",
        context: "Record number, field path",
        resolution: "Check upstream data generation for overflowed float values; null output is the documented behavior",
    },
    Explanation {
        code: "CBKE501_JSON_TYPE_MISMATCH",
        severity: "Fatal",
        description: "JSON value type doesn't match field type",
        context: "Record number, field path, expected vs actual type",
        resolution: "Fix JSON data type or schema",
    },
    Explanation {
        code: "CBKE505_SCALE_MISMATCH",
        severity: "Fatal",
        description: "Decimal scale mismatch during field encoding (JSON value has more fractional digits than the PIC clause allows)",
        context: "Field path, PIC scale, provided value scale",
        resolution: "Round or reformat the JSON value to match the field's implied decimal scale (V position)",
    },
    Explanation {
        code: "CBKE510_NUMERIC_OVERFLOW",
        severity: "Fatal",
        description: "Numeric value exceeds the field's digit capacity during encoding",
        context: "Field path, digit capacity, provided value",
        resolution: "Reduce the value or widen the PIC clause digit count",
    },
    Explanation {
        code: "CBKE515_STRING_LENGTH_VIOLATION",
        severity: "Fatal",
        description: "String value exceeds the field's declared size during encoding",
        context: "Field path, field size, encoded byte length",
        resolution: "Truncate the string or widen the PIC X(n) field size",
    },
    Explanation {
        code: "CBKE521_ARRAY_LEN_OOB",
        severity: "Fatal",
        description: "JSON array length out of bounds for OCCURS. Also raised for OCCURS DEPENDING ON (ODO) fields when the JSON counter field's value does not equal the JSON array's length, since the two are encoded independently and a mismatch would silently drop or fabricate elements on decode.",
        context: "Record number, field path, array length, min/max bounds (or counter field, counter value, array length for an ODO counter/array mismatch)",
        resolution: "Adjust array length or OCCURS bounds, or make the ODO counter value match the array length",
    },
    Explanation {
        code: "CBKE530_SIGN_SEPARATE_ENCODE_ERROR",
        severity: "Error",
        description: "SIGN SEPARATE field could not be encoded (invalid sign character or value inconsistent with the separate sign position)",
        context: "Field path, sign position (LEADING/TRAILING), provided value",
        resolution: "Ensure the JSON value's sign is representable for the SIGN SEPARATE field configuration",
    },
    Explanation {
        code: "CBKE531_FLOAT_ENCODE_OVERFLOW",
        severity: "Error",
        description: "Float encode overflow: f64 JSON value is too large for an f32 COMP-1 field",
        context: "Field path, provided value",
        resolution: "Reduce the value to f32 range or change the field to COMP-2 (f64)",
    },
    Explanation {
        code: "CBKE532_RAW_LENGTH_MISMATCH",
        severity: "Error",
        description: "Captured raw bytes do not match the fixed layout width",
        context: "Record number, expected vs captured bytes",
        resolution: "Re-decode the record to capture exact-width raw bytes, or encode from fields instead of --use-raw",
    },
    Explanation {
        code: "CBKF001_FILE_READ_ERROR",
        severity: "Fatal",
        description: "A file named on the command line could not be opened or read",
        context: "The path, and which argument it came from (copybook or input file)",
        resolution: "Check the path, spelling, and read permissions",
    },
    Explanation {
        code: "CBKF102_RECORD_LENGTH_INVALID",
        severity: "Fatal",
        description: "RDW header length references an incomplete or oversized payload",
        context: "Record number, byte offset, expected vs available bytes",
        resolution: "Verify binary transfer mode, ensure RDW length matches payload size, re-run with `--emit-raw` to inspect truncated data",
    },
    Explanation {
        code: "CBKF104_RDW_SUSPECT_ASCII",
        severity: "Warning",
        description: "RDW header suggests ASCII transfer corruption",
        context: "Record number, RDW bytes as ASCII interpretation",
        resolution: "Check file transfer mode (binary vs text)",
    },
    Explanation {
        code: "CBKF221_RDW_UNDERFLOW",
        severity: "Fatal",
        description: "RDW header or declared payload is truncated, or the RDW length is below the required minimum",
        context: "Record number, available or declared RDW length, minimum required",
        resolution: "Check data integrity or record format",
    },
    Explanation {
        code: "CBKF222_BDW_LENGTH_INVALID",
        severity: "Error (lenient), Fatal (strict)",
        description: "BDW block length is zero, below the 4-byte header minimum, or above the 32760-byte maximum (beta: VB/BDW framing)",
        context: "Block index, physical byte offset, claimed versus valid block length",
        resolution: "Check binary transfer mode, verify VB block boundaries, re-run with `--emit-raw` to inspect the truncated block",
    },
    Explanation {
        code: "CBKF223_BDW_UNDERFLOW",
        severity: "Error (lenient), Fatal (strict)",
        description: "BDW-declared block content or a nested RDW header is truncated (beta: VB/BDW framing)",
        context: "Block index, physical byte offset, claimed versus available bytes",
        resolution: "Check data integrity or record format",
    },
    Explanation {
        code: "CBKF224_RDW_BEYOND_BLOCK",
        severity: "Error (lenient), Fatal (strict)",
        description: "A nested RDW length extends beyond its containing BDW block (beta: VB/BDW framing)",
        context: "Block index, record index within block, RDW length versus remaining block bytes",
        resolution: "Check data integrity; the block is corrupt or not a VB block",
    },
    Explanation {
        code: "CBKF225_BDW_RESERVED_NONZERO",
        severity: "Warning (lenient), Fatal (strict)",
        description: "BDW reserved bytes are non-zero (beta: VB/BDW framing)",
        context: "Block index, physical byte offset, reserved bytes value",
        resolution: "Check for data corruption or use --emit-raw",
    },
    Explanation {
        code: "CBKF226_RECORD_BOUND_EXCEEDED",
        severity: "Fatal",
        description: "Record exceeds the reviewed maximum_record_length bound from an interpretation profile",
        context: "Record format and layer, record index where known, declared or observed length, selected bound",
        resolution: "Raise limits.maximum_record_length to the feed's cap or fix the over-cap record",
    },
    Explanation {
        code: "CBKI001_INVALID_STATE",
        severity: "Fatal",
        description: "Iterator detected an invalid state (e.g., fixed-format without configured LRECL)",
        context: "Record format, iterator index, configuration hint",
        resolution: "Set `schema.lrecl_fixed` or switch to `RecordFormat::Variable` before iterating",
    },
    Explanation {
        code: "CBKI002_TOO_MANY_ERRORS",
        severity: "Fatal",
        description: "Error budget exhausted; the reporter halted processing after reaching the configured maximum error count",
        context: "Configured limit, count at halt",
        resolution: "Raise the `max_errors` budget, fix the upstream records causing errors, or run in strict mode to stop at the first error",
    },
    Explanation {
        code: "CBKP001_SYNTAX",
        severity: "Fatal",
        description: "General syntax error in copybook",
        context: "Line number, column, expected vs found tokens",
        resolution: "Fix COBOL syntax in copybook",
    },
    Explanation {
        code: "CBKP011_UNSUPPORTED_CLAUSE",
        severity: "Fatal",
        description: "Unsupported COBOL clause encountered",
        context: "Clause name, field path",
        resolution: "Remove or replace unsupported clause",
    },
    Explanation {
        code: "CBKP021_ODO_NOT_TAIL",
        severity: "Fatal",
        description: "OCCURS DEPENDING ON array not at tail position",
        context: "Field path, containing group",
        resolution: "Move ODO array to end of containing group",
    },
    Explanation {
        code: "CBKP022_NESTED_ODO",
        severity: "Fatal",
        description: "OCCURS DEPENDING ON array nested inside another OCCURS/ODO array",
        context: "Field path of the nested ODO array",
        resolution: "Restructure the copybook so the ODO array is not contained in another OCCURS/ODO array (see `docs/design/NESTED_ODO_BEHAVIOR.md`)",
    },
    Explanation {
        code: "CBKP023_ODO_REDEFINES",
        severity: "Fatal",
        description: "OCCURS DEPENDING ON array inside a REDEFINES region",
        context: "Field path of the ODO array in the REDEFINES region",
        resolution: "Move the ODO array out of the REDEFINES region or replace it with a fixed OCCURS",
    },
    Explanation {
        code: "CBKP051_UNSUPPORTED_EDITED_PIC",
        severity: "Fatal",
        description: "**unsupported edited PIC token**. Triggered only by Space (`B`) insertion, which remains unsupported. All other edited PIC patterns (Z, $, +/-, CR/DB, commas, asterisk, currency) are fully supported in E1/E2/E3 phases.",
        context: "PIC clause, field path, unsupported token",
        resolution: "Remove Space (`B`) insertion from PIC clause, or use alternative formatting",
    },
    Explanation {
        code: "CBKP101_INVALID_PIC",
        severity: "Fatal",
        description: "Invalid PIC clause syntax or illegal characters in the PIC string",
        context: "PIC clause text, field path",
        resolution: "Fix the PIC clause to use valid COBOL picture characters",
    },
    Explanation {
        code: "CBKR101_FIXED_RECORD_ERROR",
        severity: "Fatal",
        description: "Error processing fixed-width record framing or I/O (fixed records and text lines)",
        context: "Record number, byte offset when available, error details",
        resolution: "Check the configured LRECL, record boundaries, line lengths under --format text, input/output integrity, and available address space",
    },
    Explanation {
        code: "CBKR201_RDW_READ_ERROR",
        severity: "Fatal",
        description: "I/O error reading a Record Descriptor Word (RDW) header or payload",
        context: "Record number, I/O error details",
        resolution: "Check file integrity and record format",
    },
    Explanation {
        code: "CBKR202_RDW_WRITE_ERROR",
        severity: "Fatal",
        description: "Error writing or flushing Record Descriptor Word (RDW) header or payload",
        context: "Record number, byte offset when available, I/O error details",
        resolution: "Check output integrity, permissions, and available disk space",
    },
    Explanation {
        code: "CBKR211_RDW_RESERVED_NONZERO",
        severity: "Warning (lenient), Fatal (strict)",
        description: "RDW reserved bytes are non-zero",
        context: "Record number, reserved bytes value",
        resolution: "Check for data corruption or use --emit-raw",
    },
    Explanation {
        code: "CBKS121_COUNTER_NOT_FOUND",
        severity: "Fatal",
        description: "ODO counter field not found or invalid",
        context: "Counter field path, ODO array path",
        resolution: "Ensure counter field exists and precedes array",
    },
    Explanation {
        code: "CBKS141_RECORD_TOO_LARGE",
        severity: "Fatal",
        description: "Computed record size exceeds maximum",
        context: "Computed size, maximum allowed",
        resolution: "Reduce record size or increase limit",
    },
    Explanation {
        code: "CBKS301_ODO_CLIPPED",
        severity: "Warning (lenient mode)",
        description: "ODO counter value exceeds maximum, clipped",
        context: "Record number, field path, actual vs maximum count",
        resolution: "Fix data or increase ODO maximum",
    },
    Explanation {
        code: "CBKS302_ODO_RAISED",
        severity: "Warning (lenient mode)",
        description: "ODO counter value below minimum, raised",
        context: "Record number, field path, actual vs minimum count",
        resolution: "Fix data or decrease ODO minimum",
    },
    Explanation {
        code: "CBKS601_RENAME_UNKNOWN_FROM",
        severity: "Fatal",
        description: "RENAMES `from` field not found in the enclosing record scope",
        context: "RENAMES alias name, missing `from` field name",
        resolution: "Ensure the field named after RENAMES exists in the same 01-level record",
    },
    Explanation {
        code: "CBKS602_RENAME_UNKNOWN_THRU",
        severity: "Fatal",
        description: "RENAMES `THRU` field not found in the enclosing record scope",
        context: "RENAMES alias name, missing `THRU` field name",
        resolution: "Ensure the field named after THRU exists in the same 01-level record",
    },
    Explanation {
        code: "CBKS603_RENAME_NOT_CONTIGUOUS",
        severity: "Fatal",
        description: "RENAMES range is not contiguous (gap between `from` and `THRU` fields)",
        context: "RENAMES alias name, `from`/`THRU` field offsets",
        resolution: "Adjust the RENAMES range so it covers a contiguous byte range. Positive alignment gaps are rejected; overlapping offsets remain valid only where the applicable REDEFINES policy permits them.",
    },
    Explanation {
        code: "CBKS604_RENAME_REVERSED_RANGE",
        severity: "Fatal",
        description: "RENAMES range is reversed (`from` field starts after the `THRU` field)",
        context: "RENAMES alias name, `from`/`THRU` field positions",
        resolution: "Swap the `from` and `THRU` field names so the range runs forward",
    },
    Explanation {
        code: "CBKS605_RENAME_FROM_CROSSES_GROUP",
        severity: "Fatal",
        description: "RENAMES `from` field crosses a group boundary",
        context: "RENAMES alias name, `from` field path, group boundary",
        resolution: "Restrict the RENAMES range so it does not straddle group boundaries (see `docs/design/RENAMES_NESTED_GROUPS.md`)",
    },
    Explanation {
        code: "CBKS606_RENAME_THRU_CROSSES_GROUP",
        severity: "Fatal",
        description: "RENAMES `THRU` field crosses a group boundary",
        context: "RENAMES alias name, `THRU` field path, group boundary",
        resolution: "Restrict the RENAMES range so it does not straddle group boundaries (see `docs/design/RENAMES_NESTED_GROUPS.md`)",
    },
    Explanation {
        code: "CBKS607_RENAME_CROSSES_OCCURS",
        severity: "Fatal",
        description: "RENAMES range crosses an OCCURS array boundary",
        context: "RENAMES alias name, OCCURS field in range",
        resolution: "Keep the RENAMES range entirely outside (or entirely inside a single element of) OCCURS arrays",
    },
    Explanation {
        code: "CBKS608_RENAME_QUALIFIED_NAME_NOT_FOUND",
        severity: "Fatal",
        description: "Qualified name in RENAMES clause (e.g., `FIELD OF GROUP`) could not be resolved",
        context: "RENAMES alias name, qualified name",
        resolution: "Verify the qualified name path matches the record structure",
    },
    Explanation {
        code: "CBKS609_RENAME_OVER_REDEFINES",
        severity: "Fatal",
        description: "RENAMES alias spans REDEFINES field(s) (R4 scenario)",
        context: "RENAMES alias name, REDEFINES fields in range",
        resolution: "Exclude REDEFINES fields from the RENAMES range or restructure the copybook",
    },
    Explanation {
        code: "CBKS610_RENAME_MULTIPLE_REDEFINES",
        severity: "Fatal",
        description: "RENAMES range spans multiple REDEFINES alternatives (R4 scenario)",
        context: "RENAMES alias name, REDEFINES alternatives in range",
        resolution: "Limit the RENAMES range to a single REDEFINES alternative",
    },
    Explanation {
        code: "CBKS611_RENAME_PARTIAL_OCCURS",
        severity: "Fatal",
        description: "RENAMES range spans partial array elements (R5 scenario)",
        context: "RENAMES alias name, OCCURS field partially covered",
        resolution: "Cover whole OCCURS arrays in the RENAMES range, not partial elements",
    },
    Explanation {
        code: "CBKS612_RENAME_ODO_NOT_SUPPORTED",
        severity: "Fatal",
        description: "RENAMES over OCCURS DEPENDING ON arrays is not supported (R5 scenario)",
        context: "RENAMES alias name, ODO field in range",
        resolution: "Remove the ODO array from the RENAMES range; RENAMES over variable-length regions is unsupported",
    },
    Explanation {
        code: "CBKS701_PROJECTION_INVALID_ODO",
        severity: "Fatal",
        description: "Selected field contains OCCURS DEPENDING ON but counter field is not accessible",
        context: "Field path, counter field path, projection selection",
        resolution: "Include the ODO counter field in selection, or select the entire parent group",
    },
    Explanation {
        code: "CBKS702_PROJECTION_UNRESOLVED_ALIAS",
        severity: "Fatal",
        description: "RENAMES alias spans fields that are not all selected",
        context: "Alias name, aliased fields, missing fields in selection",
        resolution: "Select all fields covered by the RENAMES alias, or use underlying field names directly",
    },
    Explanation {
        code: "CBKS703_PROJECTION_FIELD_NOT_FOUND",
        severity: "Fatal",
        description: "Selected field name does not exist in schema",
        context: "Field name, available fields suggestion",
        resolution: "Verify field name spelling and case sensitivity, use `copybook inspect` to list available fields",
    },
    Explanation {
        code: "CBKW001_SCHEMA_CONVERSION",
        severity: "Error",
        description: "COBOL schema could not be converted to an Arrow schema",
        context: "Schema details, conversion failure reason",
        resolution: "Check the copybook for constructs unsupported in Arrow conversion",
    },
    Explanation {
        code: "CBKW002_TYPE_MAPPING",
        severity: "Error",
        description: "A `FieldKind` has no valid Arrow type mapping",
        context: "Field path, field kind",
        resolution: "Remove or restructure the unsupported field type for Arrow output",
    },
    Explanation {
        code: "CBKW003_DECIMAL_OVERFLOW",
        severity: "Error",
        description: "Decimal precision exceeds the Decimal128 limit (38 digits)",
        context: "Field path, PIC digit count",
        resolution: "Reduce the field's digit count to 38 or fewer for Arrow output",
    },
    Explanation {
        code: "CBKW004_BATCH_BUILD",
        severity: "Error",
        description: "Arrow `RecordBatch` construction failed",
        context: "Batch details, underlying Arrow error",
        resolution: "Check input data consistency and memory availability",
    },
    Explanation {
        code: "CBKW005_PARQUET_WRITE",
        severity: "Error",
        description: "Parquet file write failed",
        context: "Output path, underlying I/O or Parquet error",
        resolution: "Check output file permissions, disk space, and Parquet writer configuration",
    },
];

/// Look up operator knowledge by full code (`CBKE501_JSON_TYPE_MISMATCH`)
/// or short code (`CBKE501`). Returns `None` for unknown identities.
#[inline]
#[must_use]
pub fn explanation_for(code: &str) -> Option<&'static Explanation> {
    let upper = code.trim().to_ascii_uppercase();
    let short = upper.split('_').next().unwrap_or(&upper);
    EXPLANATIONS
        .iter()
        .find(|row| row.code == upper || row.code.split('_').next().unwrap_or(row.code) == short)
}
