[book]
authors = ["Steven Zimmerman, CPA <git@effortlesssteven.com>"]
language = "en"
multilingual = false
src = "src"
title = "copybook-rs Documentation"

[output.html]
git-repository-url = "https://github.com/EffortlessMetrics/copybook-rs"
edit-url-template = "https://github.com/EffortlessMetrics/copybook-rs/edit/main/docs/mdbook/{path}"

[preprocessor.mermaid]
command = "mdbook-mermaid"