#!/usr/bin/env bash
# SPDX-License-Identifier: AGPL-3.0-or-later
# Post (or update) a PR comment with benchmark performance deltas.
# Usage: bench-pr-comment.sh <perf.json> <pr-number>
#
# Requires: gh CLI authenticated, bench-report binary available.
# Part of Issue #195: CI PR comment automation for bench receipts.
set -euo pipefail

PERF_JSON="${1:-target/perf.json}"
PR_NUMBER="${2:-}"
COMMENT_MARKER="<!-- copybook-bench-report -->"

if [ ! -f "$PERF_JSON" ]; then
  echo "⚠️ $PERF_JSON not found, skipping PR comment"
  exit 0
fi

if [ -z "$PR_NUMBER" ]; then
  echo "⚠️ No PR number provided, skipping PR comment"
  exit 0
fi

# Locate bench-report binary
if [ -f "./target/release/bench-report" ]; then
  BENCH_REPORT="./target/release/bench-report"
elif command -v bench-report &> /dev/null; then
  BENCH_REPORT="bench-report"
else
  echo "==> Building bench-report CLI"
  cargo build --release -p copybook-bench --bin bench-report 2>/dev/null || {
    echo "⚠️ bench-report build failed, skipping PR comment"
    exit 0
  }
  BENCH_REPORT="./target/release/bench-report"
fi

# --- Collect data ---

VALIDATE_OUTPUT=$($BENCH_REPORT validate "$PERF_JSON" 2>&1) || true
COMPARE_OUTPUT=$($BENCH_REPORT compare "$PERF_JSON" 2>&1) || true

# Extract metrics from validate output
DISPLAY_MIBPS=$(echo "$VALIDATE_OUTPUT" | grep -oP 'DISPLAY:\s*\K[\d.]+' || echo "n/a")
COMP3_MIBPS=$(echo "$VALIDATE_OUTPUT" | grep -oP 'COMP-3:\s*\K[\d.]+' || echo "n/a")

# Determine regression status
if echo "$COMPARE_OUTPUT" | grep -q "No performance regressions"; then
  REGRESSION_STATUS="✅ No regressions"
elif echo "$COMPARE_OUTPUT" | grep -q "regressions detected"; then
  REGRESSION_STATUS="❌ Regressions detected"
elif echo "$COMPARE_OUTPUT" | grep -q "No baseline"; then
  REGRESSION_STATUS="⚠️ No baseline (first run)"
else
  REGRESSION_STATUS="ℹ️ Comparison unavailable"
fi

# --- Format comment ---

COMMIT_SHA="${GITHUB_SHA:-$(git rev-parse --short HEAD 2>/dev/null || echo 'unknown')}"

COMMENT_BODY="$COMMENT_MARKER
## ⚡ Performance Report

| Metric | Current | SLO Floor | Status |
|--------|---------|-----------|--------|
| DISPLAY | ${DISPLAY_MIBPS} MiB/s | ≥80 MiB/s | $([ "$DISPLAY_MIBPS" != "n/a" ] && awk "BEGIN{exit !($DISPLAY_MIBPS >= 80)}" 2>/dev/null && echo '✅' || echo '⚠️') |
| COMP-3 | ${COMP3_MIBPS} MiB/s | ≥40 MiB/s | $([ "$COMP3_MIBPS" != "n/a" ] && awk "BEGIN{exit !($COMP3_MIBPS >= 40)}" 2>/dev/null && echo '✅' || echo '⚠️') |

**Regression check**: $REGRESSION_STATUS
**Commit**: \`$COMMIT_SHA\`

<details>
<summary>Full output</summary>

\`\`\`
$VALIDATE_OUTPUT

$COMPARE_OUTPUT
\`\`\`
</details>

---
*Generated by [bench-report](tools/copybook-bench/src/bin/bench-report.rs) · [Perf governance](docs/PERFORMANCE_GOVERNANCE.md)*"

# --- Post or update comment ---

# Check for existing comment with our marker
EXISTING_COMMENT_ID=$(gh api \
  "repos/{owner}/{repo}/issues/${PR_NUMBER}/comments" \
  --jq ".[] | select(.body | contains(\"$COMMENT_MARKER\")) | .id" \
  2>/dev/null | head -1 || echo "")

if [ -n "$EXISTING_COMMENT_ID" ]; then
  echo "==> Updating existing bench comment (ID: $EXISTING_COMMENT_ID)"
  gh api \
    --method PATCH \
    "repos/{owner}/{repo}/issues/comments/${EXISTING_COMMENT_ID}" \
    -f body="$COMMENT_BODY" > /dev/null
else
  echo "==> Posting new bench comment on PR #${PR_NUMBER}"
  gh pr comment "$PR_NUMBER" --body "$COMMENT_BODY"
fi

echo "✅ Bench PR comment posted"
